### ISSUE TITLE
Implement the BFS function

### ISSUE THREAD

**Issue by jamieRollison** [opcushing/cs225-final-project-wikiracer#2]
From the proposal:

- Function efficiency: The worst BFS will require going through every link, so the runtime will be O(E) Where E is the number of links in the dataset. Holding every point in queue/set for this worst traversal will also require O(V) space, where V is the number of pages.
- Function input: (Assume this function has access to the graph data). The function will take in a start page's title and destination page's title as strings.
- Function output: The function will output a vector of strings where the first element is the start, the final element is the destination, and the interior are the titles of the pages used to get from the start to the end.

**Comment by opcushing** [comment]
#8 : Let's close this issue once we get feedback.

**Comment by opcushing** [comment]
Reviewed by Project Manager. All done!
