### ISSUE TITLE
Implement Dijkstra's algorithm

### ISSUE THREAD

**Issue by jamieRollison** [opcushing/cs225-final-project-wikiracer#3]
From the proposal:

- Function input: The function that implements Dijkstra's (function A) would take in the graph of pages and a starting vertex. The user would interact with another function (function B) which would take in a start and end page, and calls function A using the already generated graph and the start page.
- Function output: Function A would return a vector of distances from the start to each node and a vector which determines the immediate predecessor of each vertex. Function B would return a vector generated by finding the path in the predecessor vector from function A which goes from the start to end pages.

**Comment by opcushing** [comment]
#10 : Let's close this once we get feedback from our mid-point checkin

**Comment by opcushing** [comment]
Okay, so Dijkstra's is going to be removed from our project, so closing this issue.
