### ISSUE TITLE
Data intake

### ISSUE THREAD

**Issue by jamieRollison** [opcushing/cs225-final-project-wikiracer#5]
We need to be able to intake data and store it as a graph somehow. This issue also involves data correction: we should probably parse the data and replace url encoding with readable text. The parsing functions given to us in `mp_schedule` may be helpful here.

**Comment by opcushing** [comment]
I believe all this should go in the Wikigraph file constructor (branch: `wiki-constructor`). We will need:
- [x] Open the file.
- [x] Iterate over the data.
- [x] Clean the data: Decode URL Encoded article titles.
- [x] Insert each article into the map.

Those parsing helpful functions will be useful. Let's adapt those and include them in `utilities.cc` / `utilities.hpp`

**Comment by opcushing** [comment]
We seem to have reached all the goals, so I'm marking this issue as closed. Great work!
